package com.enrichmeai.culvert.orchestration;

import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Unit tests for {@link ComposerDagRenderer}.
 *
 * <p>All tests build {@link DagSpec} directly (never via
 * {@link PipelineToDagSpec}) to prove the renderer only consumes the model.
 */
class ComposerDagRendererTest {

    private final ComposerDagRenderer renderer = new ComposerDagRenderer();

    // -------------------------------------------------------------------------
    // Composer-specific header is present
    // -------------------------------------------------------------------------

    @Test
    void composerHeader_isPresentInOutput() {
        DagSpec dag = diamondDag();

        String output = renderer.render(dag);

        assertThat(output).contains("Generated by Culvert ComposerDagRenderer");
        assertThat(output).contains("Google Cloud Composer 2");
        assertThat(output).contains(ComposerDagRenderer.COMPOSER_IMAGE_FAMILY);
        assertThat(output).contains(ComposerDagRenderer.AIRFLOW_VERSION);
    }

    @Test
    void composerHeader_containsGcsBucketDeploymentPath() {
        DagSpec dag = diamondDag();

        String output = renderer.render(dag);

        assertThat(output).contains("gs://<your-composer-bucket>/dags/" + dag.dagId() + ".py");
    }

    @Test
    void composerHeader_containsGcloudCommand() {
        DagSpec dag = diamondDag();

        String output = renderer.render(dag);

        assertThat(output).contains("gcloud composer environments storage dags import");
        assertThat(output).contains("--source=" + dag.dagId() + ".py");
    }

    // -------------------------------------------------------------------------
    // DAG body: correct task_ids and edges
    // -------------------------------------------------------------------------

    @Test
    void diamond_containsCorrectTaskIds() {
        DagSpec dag = diamondDag();

        String output = renderer.render(dag);

        assertThat(output).contains("task_id=\"A\"");
        assertThat(output).contains("task_id=\"B\"");
        assertThat(output).contains("task_id=\"C\"");
        assertThat(output).contains("task_id=\"D\"");
    }

    @Test
    void diamond_containsAllFourEdges() {
        DagSpec dag = diamondDag();

        String output = renderer.render(dag);

        assertThat(output).contains("tasks[\"A\"] >> tasks[\"B\"]");
        assertThat(output).contains("tasks[\"A\"] >> tasks[\"C\"]");
        assertThat(output).contains("tasks[\"B\"] >> tasks[\"D\"]");
        assertThat(output).contains("tasks[\"C\"] >> tasks[\"D\"]");
    }

    // -------------------------------------------------------------------------
    // Composer output is NOT identical to plain Airflow output
    // -------------------------------------------------------------------------

    @Test
    void composerOutput_differsFromAirflowOutput() {
        DagSpec dag = diamondDag();
        AirflowDagRenderer airflowRenderer = new AirflowDagRenderer();

        String airflowOutput = airflowRenderer.render(dag);
        String composerOutput = renderer.render(dag);

        // The outputs must differ — Composer has an additional header
        assertThat(composerOutput).isNotEqualTo(airflowOutput);
        // Composer output is longer (header prepended)
        assertThat(composerOutput.length()).isGreaterThan(airflowOutput.length());
        // Airflow body is embedded within the Composer output
        assertThat(composerOutput).contains(airflowOutput);
    }

    @Test
    void composerOutput_startsWithComposerHeader_notAirflowImport() {
        DagSpec dag = diamondDag();
        AirflowDagRenderer airflowRenderer = new AirflowDagRenderer();

        String airflowOutput = airflowRenderer.render(dag);
        String composerOutput = renderer.render(dag);

        // Plain Airflow starts with Python imports
        assertThat(airflowOutput).startsWith("from datetime import datetime");
        // Composer starts with its specific header comment
        assertThat(composerOutput).startsWith("# Generated by Culvert ComposerDagRenderer");
    }

    // -------------------------------------------------------------------------
    // DagSpec with null schedule → Python None propagated correctly
    // -------------------------------------------------------------------------

    @Test
    void nullSchedule_rendersAsPythonNone() {
        TaskSpec solo = new TaskSpec("task_one", "task_one", List.of(), Map.of());
        DagSpec dag = new DagSpec("manual-dag", null, List.of(solo), List.of());

        String output = renderer.render(dag);

        assertThat(output).contains("schedule=None");
    }

    // -------------------------------------------------------------------------
    // Airflow 2.9 conventions are preserved (delegated correctly)
    // -------------------------------------------------------------------------

    @Test
    void composerOutput_usesEmptyOperatorNotDummyOperator() {
        DagSpec dag = diamondDag();

        String output = renderer.render(dag);

        assertThat(output).contains("from airflow.operators.empty import EmptyOperator");
        assertThat(output).doesNotContain("DummyOperator");
    }

    @Test
    void composerOutput_usesScheduleParamNotScheduleInterval() {
        DagSpec dag = diamondDag();

        String output = renderer.render(dag);

        assertThat(output).contains("schedule=");
        assertThat(output).doesNotContain("schedule_interval=");
    }

    // -------------------------------------------------------------------------
    // Null input guard
    // -------------------------------------------------------------------------

    @Test
    void nullDagSpec_throwsNullPointerException() {
        assertThatThrownBy(() -> renderer.render(null))
                .isInstanceOf(NullPointerException.class);
    }

    // -------------------------------------------------------------------------
    // Helper
    // -------------------------------------------------------------------------

    /**
     * Diamond DagSpec: A → B, A → C, B → D, C → D.
     * Built directly — no {@link PipelineToDagSpec} involvement.
     */
    private static DagSpec diamondDag() {
        TaskSpec a = new TaskSpec("A", "A", List.of(), Map.of());
        TaskSpec b = new TaskSpec("B", "B", List.of("A"), Map.of());
        TaskSpec c = new TaskSpec("C", "C", List.of("A"), Map.of());
        TaskSpec d = new TaskSpec("D", "D", List.of("B", "C"), Map.of());
        List<DagSpec.Edge> edges = List.of(
                new DagSpec.Edge("A", "B"),
                new DagSpec.Edge("A", "C"),
                new DagSpec.Edge("B", "D"),
                new DagSpec.Edge("C", "D")
        );
        return new DagSpec("diamond-dag", "@daily", List.of(a, b, c, d), edges);
    }
}
