pipeline-beam-runner:
  image:
    repository: postgres-cdc-streaming
    tag: "0.1.0"
  parallelism:
    default: 4
  gcs:
    bucket: ""
  checkpointing:
    enabled: true
  serviceAccount:
    create: false
    name: pg-cdc-stream-runner
    gcpSaEmail: ""
