package com.enrichmeai.culvert.orchestration;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Renders a {@link DagSpec} into an Apache Airflow 2.9.x Python DAG definition.
 *
 * <h2>Target version</h2>
 * <p>This renderer targets <strong>Apache Airflow 2.9.x</strong>.
 * Specific assumptions:
 * <ul>
 *   <li>{@code from airflow.operators.empty import EmptyOperator} —
 *       {@code DummyOperator} was deprecated in 2.4 and removed in 2.9.</li>
 *   <li>{@code schedule=} parameter on {@code DAG()} — the old
 *       {@code schedule_interval=} kwarg was deprecated in 2.4.</li>
 *   <li>{@code catchup=False} — safe default; prevents backfill on first deploy.</li>
 *   <li>{@code start_date=datetime(2024, 1, 1)} — a stable, non-future anchor.
 *       Downstream users should override this via DAG-level params if needed.</li>
 * </ul>
 *
 * <h2>Output structure</h2>
 * <pre>{@code
 * # Generated by Culvert AirflowDagRenderer — do not edit by hand.
 * # Target: Apache Airflow 2.9.x
 * from datetime import datetime
 * from airflow import DAG
 * from airflow.operators.empty import EmptyOperator
 *
 * with DAG(
 *     dag_id="my_dag",
 *     schedule="@daily",
 *     start_date=datetime(2024, 1, 1),
 *     catchup=False,
 * ) as dag:
 *     tasks = {}
 *     tasks["A"] = EmptyOperator(task_id="A")
 *     tasks["B"] = EmptyOperator(task_id="B")
 *
 *     tasks["A"] >> tasks["B"]
 * }</pre>
 *
 * <h2>Usage</h2>
 * <pre>{@code
 * DagSpec spec = PipelineToDagSpec.translate(pipeline, "@daily");
 * String pySource = new AirflowDagRenderer().render(spec);
 * // Write pySource to a .py file in the Airflow DAGs folder.
 * }</pre>
 *
 * <h2>Design constraints</h2>
 * <ul>
 *   <li>Consumes only {@link DagSpec}/{@link TaskSpec} — never imports
 *       {@code Pipeline} or any runtime dependency.</li>
 *   <li>Cloud-neutral — no Airflow Java libraries (none exist); output is
 *       generated Python text.</li>
 *   <li>Task ids are referenced via a Python {@code dict} ({@code tasks["id"]})
 *       rather than bare variable names, so task ids that are not valid Python
 *       identifiers are handled safely.</li>
 * </ul>
 *
 * <p>Sprint-11 deliverable: issue #63 (T11.3).
 */
public final class AirflowDagRenderer implements DagRenderer {

    /**
     * Construct an {@code AirflowDagRenderer}.
     * The renderer is stateless; a single instance may be used concurrently.
     */
    public AirflowDagRenderer() {
        // intentionally empty — stateless
    }

    /**
     * Render the {@link DagSpec} as an Airflow 2.9.x Python DAG definition.
     *
     * @param dagSpec the scheduler-agnostic DAG to render. Non-null.
     * @return a Python source string suitable for placement in the Airflow
     *         {@code dags/} directory.
     * @throws NullPointerException if {@code dagSpec} is null.
     */
    @Override
    public String render(DagSpec dagSpec) {
        Objects.requireNonNull(dagSpec, "dagSpec must not be null");
        return buildDagBody(dagSpec);
    }

    /**
     * Build the Python DAG body from the given {@link DagSpec}.
     * Package-private so {@link ComposerDagRenderer} can reuse it.
     *
     * @param dagSpec the spec to render.
     * @return the Airflow Python DAG source (without any wrapper header).
     */
    String buildDagBody(DagSpec dagSpec) {
        String scheduleValue = dagSpec.schedule() != null
                ? "\"" + dagSpec.schedule() + "\""
                : "None";

        List<String> lines = new ArrayList<>();

        lines.add("from datetime import datetime");
        lines.add("from airflow import DAG");
        lines.add("from airflow.operators.empty import EmptyOperator");
        lines.add("");
        lines.add("with DAG(");
        lines.add("    dag_id=\"" + dagSpec.dagId() + "\",");
        lines.add("    schedule=" + scheduleValue + ",");
        lines.add("    start_date=datetime(2024, 1, 1),");
        lines.add("    catchup=False,");
        lines.add(") as dag:");
        lines.add("    tasks = {}");

        for (TaskSpec task : dagSpec.tasks()) {
            lines.add("    tasks[\"" + task.taskId() + "\"] = "
                    + "EmptyOperator(task_id=\"" + task.taskId() + "\")");
        }

        if (!dagSpec.edges().isEmpty()) {
            lines.add("");
            for (DagSpec.Edge edge : dagSpec.edges()) {
                lines.add("    tasks[\"" + edge.fromTaskId() + "\"] "
                        + ">> tasks[\"" + edge.toTaskId() + "\"]");
            }
        }

        return String.join("\n", lines) + "\n";
    }
}
