package com.enrichmeai.culvert.orchestration;

import java.util.Objects;

/**
 * Renders a {@link DagSpec} into a Cloud Composer-targeted Python DAG file.
 *
 * <h2>How this differs from {@link AirflowDagRenderer}</h2>
 * <p>Cloud Composer runs a managed Airflow environment on Google Kubernetes
 * Engine (GKE).  The DAG <em>body</em> is identical to a plain Airflow DAG —
 * operators, schedule, dependencies are the same Python constructs.  The
 * difference is in <em>packaging and deployment context</em>:
 * <ol>
 *   <li><strong>GCS deployment header</strong> — a block comment at the top
 *       of the file documents the target Cloud Storage bucket/path where
 *       the file must be uploaded ({@code gs://<composer-bucket>/dags/}).
 *       CI/CD tooling (e.g. the {@code gcloud composer environments storage}
 *       command) reads this file and places it in the correct location.</li>
 *   <li><strong>Composer image + Airflow-version pin</strong> — a comment
 *       records the Composer image family and the Airflow version the DAG
 *       was generated for, so operators know which Composer environment
 *       version to target.</li>
 *   <li><strong>Generator tag</strong> — the header identifies this as a
 *       Culvert Composer output rather than a plain Airflow output, making
 *       provenance auditable.</li>
 * </ol>
 *
 * <p>The DAG body itself is delegated to {@link AirflowDagRenderer} — no
 * duplication of the generation logic.
 *
 * <h2>Output structure</h2>
 * <pre>{@code
 * # Generated by Culvert ComposerDagRenderer — do not edit by hand.
 * # Target: Google Cloud Composer 2 (Airflow 2.9.x)
 * # Composer image family: composer-2-airflow-2
 * #
 * # Deploy to Cloud Composer by uploading this file to:
 * #   gs://<your-composer-bucket>/dags/my_dag.py
 * #
 * # Command:
 * #   gcloud composer environments storage dags import \
 * #       --environment=<ENV_NAME> --location=<REGION> \
 * #       --source=my_dag.py
 * #
 * from datetime import datetime
 * from airflow import DAG
 * from airflow.operators.empty import EmptyOperator
 *
 * with DAG(
 *     dag_id="my_dag",
 *     ...
 * ) as dag:
 *     ...
 * }</pre>
 *
 * <h2>Usage</h2>
 * <pre>{@code
 * DagSpec spec = PipelineToDagSpec.translate(pipeline, "@daily");
 * String pySource = new ComposerDagRenderer().render(spec);
 * // Upload pySource to gs://<composer-bucket>/dags/<dagId>.py
 * }</pre>
 *
 * <h2>Design constraints</h2>
 * <ul>
 *   <li>Consumes only {@link DagSpec}/{@link TaskSpec} — never imports
 *       {@code Pipeline} or any runtime dependency.</li>
 *   <li>Cloud-neutral at the Java level; the output text references GCS
 *       paths, but no GCP SDK is imported.</li>
 *   <li>Delegates DAG body generation to {@link AirflowDagRenderer} to
 *       keep the two renderers in sync without duplicating logic.</li>
 * </ul>
 *
 * <p>Sprint-11 deliverable: issue #63 (T11.3).
 */
public final class ComposerDagRenderer implements DagRenderer {

    /** Airflow version documented in Composer-specific headers. */
    static final String AIRFLOW_VERSION = "2.9.x";

    /** Cloud Composer image family documented in the header. */
    static final String COMPOSER_IMAGE_FAMILY = "composer-2-airflow-2";

    private final AirflowDagRenderer airflowDagRenderer;

    /**
     * Construct a {@code ComposerDagRenderer} using the default
     * {@link AirflowDagRenderer}.
     */
    public ComposerDagRenderer() {
        this.airflowDagRenderer = new AirflowDagRenderer();
    }

    /**
     * Construct a {@code ComposerDagRenderer} with a supplied
     * {@link AirflowDagRenderer} (for testing or custom configuration).
     *
     * @param airflowDagRenderer the renderer to delegate DAG body generation to.
     *                           Non-null.
     */
    public ComposerDagRenderer(AirflowDagRenderer airflowDagRenderer) {
        Objects.requireNonNull(airflowDagRenderer, "airflowDagRenderer must not be null");
        this.airflowDagRenderer = airflowDagRenderer;
    }

    /**
     * Render the {@link DagSpec} as a Cloud Composer-targeted Python DAG file.
     *
     * <p>The output begins with a Composer-specific packaging header, followed
     * by the Airflow DAG body (generated by {@link AirflowDagRenderer}).
     *
     * @param dagSpec the scheduler-agnostic DAG to render. Non-null.
     * @return a Python source string with a Composer deployment header,
     *         suitable for uploading to a Composer environment's GCS DAGs folder.
     * @throws NullPointerException if {@code dagSpec} is null.
     */
    @Override
    public String render(DagSpec dagSpec) {
        Objects.requireNonNull(dagSpec, "dagSpec must not be null");

        String header = buildComposerHeader(dagSpec);
        String body = airflowDagRenderer.buildDagBody(dagSpec);
        return header + body;
    }

    private static String buildComposerHeader(DagSpec dagSpec) {
        return "# Generated by Culvert ComposerDagRenderer — do not edit by hand.\n"
                + "# Target: Google Cloud Composer 2 (Airflow " + AIRFLOW_VERSION + ")\n"
                + "# Composer image family: " + COMPOSER_IMAGE_FAMILY + "\n"
                + "#\n"
                + "# Deploy to Cloud Composer by uploading this file to:\n"
                + "#   gs://<your-composer-bucket>/dags/" + dagSpec.dagId() + ".py\n"
                + "#\n"
                + "# Command:\n"
                + "#   gcloud composer environments storage dags import \\\n"
                + "#       --environment=<ENV_NAME> --location=<REGION> \\\n"
                + "#       --source=" + dagSpec.dagId() + ".py\n"
                + "#\n";
    }
}
