package com.enrichmeai.culvert.orchestration;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Renders a {@link DagSpec} into a DAG whose tasks run on a chosen
 * {@link ExecutionSubstrate}, with the pipeline code unchanged between them.
 *
 * <h2>Why one renderer and not three</h2>
 * <p>{@link ExecutionSubstrate#COMPOSER_2_GKE_PODS} and
 * {@link ExecutionSubstrate#COMPOSER_3} emit the <em>same</em>
 * {@code KubernetesPodOperator} task with the same
 * {@code config_file="/home/airflow/composer_kube_config"} — that idiom is
 * unchanged on Composer 3, despite the GKE cluster moving into the tenant
 * project. What differs is the constraint profile, which this renderer
 * enforces. {@link ExecutionSubstrate#CLOUD_RUN_JOBS} is a genuinely different
 * operator and gets a different emission path.
 *
 * <h2>Enforcement, not documentation</h2>
 * <p>Composer 3 silently ignores a requested namespace and runs the pod in
 * {@code composer-user-workloads} anyway. A renderer that passed the namespace
 * through would produce a DAG that deploys cleanly, runs, and puts the
 * workload somewhere other than where its author asked — discoverable only in
 * production. This class refuses instead, and says why.
 *
 * <h2>Task parameters</h2>
 * <p>Read from {@link TaskSpec#params()}:
 * <ul>
 *   <li>{@code image} — container image. Required for every substrate.</li>
 *   <li>{@code namespace} — pod namespace. Pod substrates only, and rejected
 *       on Composer 3.</li>
 *   <li>{@code sidecars} — number of extra sidecar containers. Pod substrates
 *       only; capped at 1 on Composer 3.</li>
 *   <li>{@code cloud_run_job} / {@code region} — Cloud Run job name and region.
 *       Required for {@link ExecutionSubstrate#CLOUD_RUN_JOBS}.</li>
 * </ul>
 */
public final class SubstrateDagRenderer implements DagRenderer {

    /**
     * Composer mounts a kubeconfig for its own environment cluster at this
     * path, on Composer 2 and Composer 3 alike. Hardcoded rather than
     * configurable because it is Composer's contract, not the user's choice.
     */
    private static final String COMPOSER_KUBE_CONFIG = "/home/airflow/composer_kube_config";

    /** The only sidecar name Composer 3 accepts. */
    private static final String ALLOWED_SIDECAR = "airflow-xcom-sidecar";

    private final ExecutionSubstrate substrate;

    public SubstrateDagRenderer(ExecutionSubstrate substrate) {
        this.substrate = Objects.requireNonNull(substrate, "substrate must not be null");
    }

    /** The substrate this renderer targets. */
    public ExecutionSubstrate substrate() {
        return substrate;
    }

    @Override
    public String render(DagSpec dagSpec) {
        Objects.requireNonNull(dagSpec, "dagSpec must not be null");

        List<String> lines = new ArrayList<>();
        lines.addAll(header(dagSpec));
        lines.addAll(imports());
        lines.add("");
        lines.add("with DAG(");
        lines.add("    dag_id=\"" + dagSpec.dagId() + "\",");
        lines.add("    schedule=" + (dagSpec.schedule() != null
                ? "\"" + dagSpec.schedule() + "\"" : "None") + ",");
        lines.add("    start_date=datetime(2024, 1, 1),");
        lines.add("    catchup=False,");
        lines.add(") as dag:");
        lines.add("    tasks = {}");

        for (TaskSpec task : dagSpec.tasks()) {
            lines.addAll(renderTask(task));
        }

        if (!dagSpec.edges().isEmpty()) {
            lines.add("");
            for (DagSpec.Edge edge : dagSpec.edges()) {
                lines.add("    tasks[\"" + edge.fromTaskId() + "\"] "
                        + ">> tasks[\"" + edge.toTaskId() + "\"]");
            }
        }

        return String.join("\n", lines) + "\n";
    }

    private List<String> header(DagSpec dagSpec) {
        List<String> lines = new ArrayList<>();
        lines.add("# Generated by Culvert SubstrateDagRenderer - do not edit by hand.");
        lines.add("# Execution substrate: " + substrate.name());
        if (substrate.composerImageVersion() != null) {
            lines.add("# Composer image family: " + substrate.composerImageVersion());
        }
        if (substrate == ExecutionSubstrate.COMPOSER_3) {
            lines.add("#");
            lines.add("# Composer 3 notes: the environment's GKE cluster lives in the tenant");
            lines.add("# project and is not configurable. Pods always run in the");
            lines.add("# " + substrate.podNamespace() + " namespace. Kubernetes Secrets and");
            lines.add("# ConfigMaps cannot be created through the Kubernetes API - provision");
            lines.add("# them with gcloud, Terraform, or the Composer API instead.");
        }
        if (substrate == ExecutionSubstrate.CLOUD_RUN_JOBS) {
            lines.add("#");
            lines.add("# Cloud Run is NOT available on GCP 1.0 / CNE. This DAG targets the");
            lines.add("# GCP 2.0 landing zone only.");
        }
        lines.add("#");
        lines.add("# Deploy to Cloud Composer by uploading this file to:");
        lines.add("#   gs://<your-composer-bucket>/dags/" + dagSpec.dagId() + ".py");
        lines.add("");
        return lines;
    }

    private List<String> imports() {
        List<String> lines = new ArrayList<>();
        lines.add("from datetime import datetime");
        lines.add("from airflow import DAG");
        if (substrate.launchesPods()) {
            lines.add("from airflow.providers.cncf.kubernetes.operators.pod import "
                    + "KubernetesPodOperator");
        } else {
            lines.add("from airflow.providers.google.cloud.operators.cloud_run import "
                    + "CloudRunExecuteJobOperator");
        }
        return lines;
    }

    private List<String> renderTask(TaskSpec task) {
        return substrate.launchesPods() ? renderPodTask(task) : renderCloudRunTask(task);
    }

    private List<String> renderPodTask(TaskSpec task) {
        String image = requiredParam(task, "image");
        String namespace = resolveNamespace(task);
        int sidecars = intParam(task, "sidecars", 0);

        if (sidecars > substrate.maxSidecars()) {
            throw new IllegalArgumentException(
                    "Task '" + task.taskId() + "' requests " + sidecars + " sidecar(s), but "
                            + substrate.name() + " allows at most " + substrate.maxSidecars()
                            + (substrate == ExecutionSubstrate.COMPOSER_3
                            ? " (and only if named '" + ALLOWED_SIDECAR + "')." : ".")
                            + " Rendering it anyway would produce a DAG that fails at run time"
                            + " on the cluster rather than here.");
        }

        List<String> lines = new ArrayList<>();
        lines.add("    tasks[\"" + task.taskId() + "\"] = KubernetesPodOperator(");
        lines.add("        task_id=\"" + task.taskId() + "\",");
        lines.add("        name=\"" + task.taskId() + "\",");
        lines.add("        namespace=\"" + namespace + "\",");
        lines.add("        image=\"" + image + "\",");
        // Composer mounts this kubeconfig on both 2 and 3; without it the
        // operator would look for in-cluster credentials the Airflow worker
        // does not have.
        lines.add("        config_file=\"" + COMPOSER_KUBE_CONFIG + "\",");
        lines.add("        is_delete_operator_pod=True,");
        lines.add("    )");
        return lines;
    }

    private String resolveNamespace(TaskSpec task) {
        Serializable requested = task.params().get("namespace");
        if (requested == null) {
            return substrate.podNamespace() != null ? substrate.podNamespace() : "default";
        }
        if (!substrate.allowsCustomNamespace()) {
            throw new IllegalArgumentException(
                    "Task '" + task.taskId() + "' requests namespace '" + requested + "', but "
                            + substrate.name() + " always runs pods in '"
                            + substrate.podNamespace() + "' and silently ignores any other "
                            + "namespace. Refusing rather than rendering a DAG that puts the "
                            + "workload somewhere other than where it says.");
        }
        return String.valueOf(requested);
    }

    private List<String> renderCloudRunTask(TaskSpec task) {
        String job = requiredParam(task, "cloud_run_job");
        String region = requiredParam(task, "region");
        String project = String.valueOf(
                task.params().getOrDefault("project_id", "{{ var.value.gcp_project }}"));

        List<String> lines = new ArrayList<>();
        lines.add("    tasks[\"" + task.taskId() + "\"] = CloudRunExecuteJobOperator(");
        lines.add("        task_id=\"" + task.taskId() + "\",");
        lines.add("        project_id=\"" + project + "\",");
        lines.add("        region=\"" + region + "\",");
        lines.add("        job_name=\"" + job + "\",");
        lines.add("    )");
        return lines;
    }

    private static String requiredParam(TaskSpec task, String key) {
        Map<String, Serializable> params = task.params();
        Serializable value = params.get(key);
        if (value == null || String.valueOf(value).isBlank()) {
            throw new IllegalArgumentException(
                    "Task '" + task.taskId() + "' is missing required param '" + key + "'.");
        }
        return String.valueOf(value);
    }

    private static int intParam(TaskSpec task, String key, int fallback) {
        Serializable value = task.params().get(key);
        if (value == null) {
            return fallback;
        }
        if (value instanceof Number number) {
            return number.intValue();
        }
        return Integer.parseInt(String.valueOf(value).trim());
    }
}
