apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pipeline-beam-runner.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.gcpSaEmail }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcpSaEmail }}
{{- end }}
