# Generated by Culvert SubstrateDagRenderer - do not edit by hand.
# Execution substrate: CLOUD_RUN_JOBS
#
# Cloud Run is NOT available on GCP 1.0 / CNE. This DAG targets the
# GCP 2.0 landing zone only.
#
# Deploy to Cloud Composer by uploading this file to:
#   gs://<your-composer-bucket>/dags/orders_run.py

from datetime import datetime
from airflow import DAG
from airflow.providers.google.cloud.operators.cloud_run import CloudRunExecuteJobOperator

with DAG(
    dag_id="orders_run",
    schedule="0 3 * * *",
    start_date=datetime(2024, 1, 1),
    catchup=False,
) as dag:
    tasks = {}
    tasks["ingest"] = CloudRunExecuteJobOperator(
        task_id="ingest",
        project_id="{{ var.value.gcp_project }}",
        region="europe-west2",
        job_name="ingest-job",
    )
