# Generated by Culvert SubstrateDagRenderer - do not edit by hand.
# Execution substrate: COMPOSER_2_GKE_PODS
# Composer image family: composer-2-airflow-2
#
# Deploy to Cloud Composer by uploading this file to:
#   gs://<your-composer-bucket>/dags/orders_pods.py

from datetime import datetime
from airflow import DAG
from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator

with DAG(
    dag_id="orders_pods",
    schedule=None,
    start_date=datetime(2024, 1, 1),
    catchup=False,
) as dag:
    tasks = {}
    tasks["ingest"] = KubernetesPodOperator(
        task_id="ingest",
        name="ingest",
        namespace="default",
        image="europe-docker.pkg.dev/p/r/ingest:1",
        config_file="/home/airflow/composer_kube_config",
        is_delete_operator_pod=True,
    )
    tasks["transform"] = KubernetesPodOperator(
        task_id="transform",
        name="transform",
        namespace="default",
        image="europe-docker.pkg.dev/p/r/transform:1",
        config_file="/home/airflow/composer_kube_config",
        is_delete_operator_pod=True,
    )

    tasks["ingest"] >> tasks["transform"]
