# Generated by Culvert SubstrateDagRenderer - do not edit by hand.
# Execution substrate: COMPOSER_3
# Composer image family: composer-3-airflow-2
#
# Composer 3 notes: the environment's GKE cluster lives in the tenant
# project and is not configurable. Pods always run in the
# composer-user-workloads namespace. Kubernetes Secrets and
# ConfigMaps cannot be created through the Kubernetes API - provision
# them with gcloud, Terraform, or the Composer API instead.
#
# Deploy to Cloud Composer by uploading this file to:
#   gs://<your-composer-bucket>/dags/orders_pods.py

from datetime import datetime
from airflow import DAG
from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator

with DAG(
    dag_id="orders_pods",
    schedule=None,
    start_date=datetime(2024, 1, 1),
    catchup=False,
) as dag:
    tasks = {}
    tasks["ingest"] = KubernetesPodOperator(
        task_id="ingest",
        name="ingest",
        namespace="composer-user-workloads",
        image="europe-docker.pkg.dev/p/r/ingest:1",
        config_file="/home/airflow/composer_kube_config",
        is_delete_operator_pod=True,
    )
    tasks["transform"] = KubernetesPodOperator(
        task_id="transform",
        name="transform",
        namespace="composer-user-workloads",
        image="europe-docker.pkg.dev/p/r/transform:1",
        config_file="/home/airflow/composer_kube_config",
        is_delete_operator_pod=True,
    )

    tasks["ingest"] >> tasks["transform"]
