# Generated by Culvert ComposerDagRenderer — do not edit by hand.
# Target: Google Cloud Composer 2 (Airflow 2.9.x)
# Composer image family: composer-2-airflow-2
#
# Deploy to Cloud Composer by uploading this file to:
#   gs://<your-composer-bucket>/dags/reference_e2e_control_plane.py
#
# Command:
#   gcloud composer environments storage dags import \
#       --environment=<ENV_NAME> --location=<REGION> \
#       --source=reference_e2e_control_plane.py
#
from datetime import datetime
from airflow import DAG
from airflow.exceptions import AirflowException
from airflow.operators.python import PythonOperator

# Stage-gate checker: an object with completion(unit=, stage=, period=) that
# returns None until the stage is completed (StageClaim.completion, #197).
_stage_gate = __import__("reference_e2e_control_plane_stores").stage_claim()
# Readiness checker: an object with not_ready(unit=, period=) that returns the
# inputs not yet ready, empty only when all are (InputReadiness.readiness, #230).
_input_readiness = __import__("reference_e2e_control_plane_stores").input_readiness()

# Job-control repository — assign your JobControlRepository impl here.
_job_ctrl = __import__("reference_e2e_control_plane_stores").job_control()

with DAG(
    dag_id="reference_e2e_control_plane",
    schedule="@daily",
    start_date=datetime(2024, 1, 1),
    catchup=False,
    max_active_tasks=2,
) as dag:
    tasks = {}

    def _callable_orders__load(**context):
        run_id = context["run_id"]
        _job_ctrl.create_job(
            run_id=run_id,
            system_id="reference-e2e",
            pipeline_name="reference_e2e_control_plane",
            extract_date=context["ds"],
            status="created",
        )
        _job_ctrl.update_status(
            run_id=run_id,
            status="running",
            total_records=None,
        )
        try:
            pass  # orders__load task body
            _job_ctrl.update_status(
                run_id=run_id,
                status="succeeded",
                total_records=None,
            )
        except Exception as _exc:
            _job_ctrl.mark_failed(
                run_id=run_id,
                error_code="TASK_FAILED",
                error_message=str(_exc),
                failure_stage="unknown",
                error_file_path=None,
            )
            raise
    tasks["orders__load"] = PythonOperator(task_id="orders__load", python_callable=_callable_orders__load)

    def _callable_orders__validate(**context):
        _waiting_on = [
            _stage for _stage in ["load"]
            if _stage_gate.completion(unit=context["task"].task_id.split("__")[0], stage=_stage, period=context["ds"]) is None
        ]
        if _waiting_on:
            raise AirflowException(
                "Gate closed for task 'orders__validate': not completed: " + ", ".join(_waiting_on)
            )
        run_id = context["run_id"]
        _job_ctrl.update_status(
            run_id=run_id,
            status="running",
            total_records=None,
        )
        try:
            pass  # orders__validate task body
            _job_ctrl.update_status(
                run_id=run_id,
                status="succeeded",
                total_records=None,
            )
        except Exception as _exc:
            _job_ctrl.mark_failed(
                run_id=run_id,
                error_code="TASK_FAILED",
                error_message=str(_exc),
                failure_stage="unknown",
                error_file_path=None,
            )
            raise
    tasks["orders__validate"] = PythonOperator(task_id="orders__validate", python_callable=_callable_orders__validate)

    def _callable_orders__publish(**context):
        _waiting_on = [
            _stage for _stage in ["load", "validate"]
            if _stage_gate.completion(unit=context["task"].task_id.split("__")[0], stage=_stage, period=context["ds"]) is None
        ]
        if _waiting_on:
            raise AirflowException(
                "Gate closed for task 'orders__publish': not completed: " + ", ".join(_waiting_on)
            )
        _not_ready = list(_input_readiness.not_ready(unit=context["task"].task_id.split("__")[0], period=context["ds"]))
        if _not_ready:
            raise AirflowException(
                "Gate closed for task 'orders__publish': inputs not ready: " + ", ".join(str(_i) for _i in _not_ready)
            )
        run_id = context["run_id"]
        _job_ctrl.update_status(
            run_id=run_id,
            status="running",
            total_records=None,
        )
        try:
            pass  # orders__publish task body
            _job_ctrl.update_status(
                run_id=run_id,
                status="succeeded",
                total_records=None,
            )
        except Exception as _exc:
            _job_ctrl.mark_failed(
                run_id=run_id,
                error_code="TASK_FAILED",
                error_message=str(_exc),
                failure_stage="unknown",
                error_file_path=None,
            )
            raise
    tasks["orders__publish"] = PythonOperator(task_id="orders__publish", python_callable=_callable_orders__publish)

    def _callable_customers__load(**context):
        run_id = context["run_id"]
        _job_ctrl.update_status(
            run_id=run_id,
            status="running",
            total_records=None,
        )
        try:
            pass  # customers__load task body
            _job_ctrl.update_status(
                run_id=run_id,
                status="succeeded",
                total_records=None,
            )
        except Exception as _exc:
            _job_ctrl.mark_failed(
                run_id=run_id,
                error_code="TASK_FAILED",
                error_message=str(_exc),
                failure_stage="unknown",
                error_file_path=None,
            )
            raise
    tasks["customers__load"] = PythonOperator(task_id="customers__load", python_callable=_callable_customers__load)

    def _callable_customers__validate(**context):
        _waiting_on = [
            _stage for _stage in ["load"]
            if _stage_gate.completion(unit=context["task"].task_id.split("__")[0], stage=_stage, period=context["ds"]) is None
        ]
        if _waiting_on:
            raise AirflowException(
                "Gate closed for task 'customers__validate': not completed: " + ", ".join(_waiting_on)
            )
        run_id = context["run_id"]
        _job_ctrl.update_status(
            run_id=run_id,
            status="running",
            total_records=None,
        )
        try:
            pass  # customers__validate task body
            _job_ctrl.update_status(
                run_id=run_id,
                status="succeeded",
                total_records=None,
            )
        except Exception as _exc:
            _job_ctrl.mark_failed(
                run_id=run_id,
                error_code="TASK_FAILED",
                error_message=str(_exc),
                failure_stage="unknown",
                error_file_path=None,
            )
            raise
    tasks["customers__validate"] = PythonOperator(task_id="customers__validate", python_callable=_callable_customers__validate)

    def _callable_customers__publish(**context):
        _waiting_on = [
            _stage for _stage in ["load", "validate"]
            if _stage_gate.completion(unit=context["task"].task_id.split("__")[0], stage=_stage, period=context["ds"]) is None
        ]
        if _waiting_on:
            raise AirflowException(
                "Gate closed for task 'customers__publish': not completed: " + ", ".join(_waiting_on)
            )
        _not_ready = list(_input_readiness.not_ready(unit=context["task"].task_id.split("__")[0], period=context["ds"]))
        if _not_ready:
            raise AirflowException(
                "Gate closed for task 'customers__publish': inputs not ready: " + ", ".join(str(_i) for _i in _not_ready)
            )
        run_id = context["run_id"]
        _job_ctrl.update_status(
            run_id=run_id,
            status="running",
            total_records=None,
        )
        try:
            pass  # customers__publish task body
            _job_ctrl.update_status(
                run_id=run_id,
                status="succeeded",
                total_records=None,
            )
        except Exception as _exc:
            _job_ctrl.mark_failed(
                run_id=run_id,
                error_code="TASK_FAILED",
                error_message=str(_exc),
                failure_stage="unknown",
                error_file_path=None,
            )
            raise
    tasks["customers__publish"] = PythonOperator(task_id="customers__publish", python_callable=_callable_customers__publish)

    def _callable_products__load(**context):
        run_id = context["run_id"]
        _job_ctrl.update_status(
            run_id=run_id,
            status="running",
            total_records=None,
        )
        try:
            pass  # products__load task body
            _job_ctrl.update_status(
                run_id=run_id,
                status="succeeded",
                total_records=None,
            )
        except Exception as _exc:
            _job_ctrl.mark_failed(
                run_id=run_id,
                error_code="TASK_FAILED",
                error_message=str(_exc),
                failure_stage="unknown",
                error_file_path=None,
            )
            raise
    tasks["products__load"] = PythonOperator(task_id="products__load", python_callable=_callable_products__load)

    def _callable_products__validate(**context):
        _waiting_on = [
            _stage for _stage in ["load"]
            if _stage_gate.completion(unit=context["task"].task_id.split("__")[0], stage=_stage, period=context["ds"]) is None
        ]
        if _waiting_on:
            raise AirflowException(
                "Gate closed for task 'products__validate': not completed: " + ", ".join(_waiting_on)
            )
        run_id = context["run_id"]
        _job_ctrl.update_status(
            run_id=run_id,
            status="running",
            total_records=None,
        )
        try:
            pass  # products__validate task body
            _job_ctrl.update_status(
                run_id=run_id,
                status="succeeded",
                total_records=None,
            )
        except Exception as _exc:
            _job_ctrl.mark_failed(
                run_id=run_id,
                error_code="TASK_FAILED",
                error_message=str(_exc),
                failure_stage="unknown",
                error_file_path=None,
            )
            raise
    tasks["products__validate"] = PythonOperator(task_id="products__validate", python_callable=_callable_products__validate)

    def _callable_products__publish(**context):
        _waiting_on = [
            _stage for _stage in ["load", "validate"]
            if _stage_gate.completion(unit=context["task"].task_id.split("__")[0], stage=_stage, period=context["ds"]) is None
        ]
        if _waiting_on:
            raise AirflowException(
                "Gate closed for task 'products__publish': not completed: " + ", ".join(_waiting_on)
            )
        _not_ready = list(_input_readiness.not_ready(unit=context["task"].task_id.split("__")[0], period=context["ds"]))
        if _not_ready:
            raise AirflowException(
                "Gate closed for task 'products__publish': inputs not ready: " + ", ".join(str(_i) for _i in _not_ready)
            )
        run_id = context["run_id"]
        _job_ctrl.update_status(
            run_id=run_id,
            status="running",
            total_records=None,
        )
        try:
            pass  # products__publish task body
            _job_ctrl.update_status(
                run_id=run_id,
                status="succeeded",
                total_records=None,
            )
        except Exception as _exc:
            _job_ctrl.mark_failed(
                run_id=run_id,
                error_code="TASK_FAILED",
                error_message=str(_exc),
                failure_stage="unknown",
                error_file_path=None,
            )
            raise
    tasks["products__publish"] = PythonOperator(task_id="products__publish", python_callable=_callable_products__publish)

    tasks["orders__load"] >> tasks["orders__validate"]
    tasks["orders__validate"] >> tasks["orders__publish"]
    tasks["customers__load"] >> tasks["customers__validate"]
    tasks["customers__validate"] >> tasks["customers__publish"]
    tasks["products__load"] >> tasks["products__validate"]
    tasks["products__validate"] >> tasks["products__publish"]
